[2023-10-21T15:57:28.072+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_day18.load_dataframe_into_postgresql manual__2023-10-21T15:57:10.827261+00:00 [queued]>
[2023-10-21T15:57:28.085+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_day18.load_dataframe_into_postgresql manual__2023-10-21T15:57:10.827261+00:00 [queued]>
[2023-10-21T15:57:28.085+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-21T15:57:28.101+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_dataframe_into_postgresql> on 2023-10-21 15:57:10.827261+00:00
[2023-10-21T15:57:28.106+0000] {standard_task_runner.py:57} INFO - Started process 4670 to run task
[2023-10-21T15:57:28.110+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_day18', 'load_dataframe_into_postgresql', 'manual__2023-10-21T15:57:10.827261+00:00', '--job-id', '80', '--raw', '--subdir', 'DAGS_FOLDER/ETL_day18.py', '--cfg-path', '/tmp/tmp3b5f8lu4']
[2023-10-21T15:57:28.113+0000] {standard_task_runner.py:85} INFO - Job 80: Subtask load_dataframe_into_postgresql
[2023-10-21T15:57:28.165+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_day18.load_dataframe_into_postgresql manual__2023-10-21T15:57:10.827261+00:00 [running]> on host 90cf752d844d
[2023-10-21T15:57:28.248+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kel11' AIRFLOW_CTX_DAG_ID='etl_day18' AIRFLOW_CTX_TASK_ID='load_dataframe_into_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T15:57:10.827261+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-21T15:57:10.827261+00:00'
[2023-10-21T15:57:28.295+0000] {warnings.py:109} WARNING - /opt/***/dags/ETL_day18.py:97: UserWarning: pandas only supports SQLAlchemy connectable (engine/connection) or database string URI or sqlite3 DBAPI2 connection. Other DBAPI2 objects are not tested. Please consider using SQLAlchemy.
  return df.to_sql('public.latest', hook, if_exists='replace', chunksize=1000)

[2023-10-21T15:57:28.297+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_day18.py", line 97, in load_dataframe_into_postgresql
    return df.to_sql('public.latest', hook, if_exists='replace', chunksize=1000)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 769, in to_sql
    return pandas_sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2378, in to_sql
    table.create()
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 903, in create
    if self.exists():
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 889, in exists
    return self.pd_sql.has_table(self.name, self.schema)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2385, in has_table
    return len(self.execute(query, [name]).fetchall()) > 0
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 2200, in execute
    cur = self.con.cursor()
AttributeError: 'PostgresHook' object has no attribute 'cursor'
[2023-10-21T15:57:28.310+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_day18, task_id=load_dataframe_into_postgresql, execution_date=20231021T155710, start_date=20231021T155728, end_date=20231021T155728
[2023-10-21T15:57:28.328+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 80 for task load_dataframe_into_postgresql ('PostgresHook' object has no attribute 'cursor'; 4670)
[2023-10-21T15:57:28.373+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-21T15:57:28.398+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
