[2023-10-22T08:43:18.848+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_day18.load_dataframe_into_postgresql manual__2023-10-22T08:43:05.401349+00:00 [queued]>
[2023-10-22T08:43:18.864+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_day18.load_dataframe_into_postgresql manual__2023-10-22T08:43:05.401349+00:00 [queued]>
[2023-10-22T08:43:18.865+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-22T08:43:18.881+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_dataframe_into_postgresql> on 2023-10-22 08:43:05.401349+00:00
[2023-10-22T08:43:18.888+0000] {standard_task_runner.py:57} INFO - Started process 641 to run task
[2023-10-22T08:43:18.894+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_day18', 'load_dataframe_into_postgresql', 'manual__2023-10-22T08:43:05.401349+00:00', '--job-id', '184', '--raw', '--subdir', 'DAGS_FOLDER/ETL_day18.py', '--cfg-path', '/tmp/tmpzj_5okml']
[2023-10-22T08:43:18.899+0000] {standard_task_runner.py:85} INFO - Job 184: Subtask load_dataframe_into_postgresql
[2023-10-22T08:43:18.967+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_day18.load_dataframe_into_postgresql manual__2023-10-22T08:43:05.401349+00:00 [running]> on host 90cf752d844d
[2023-10-22T08:43:19.130+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kel11' AIRFLOW_CTX_DAG_ID='etl_day18' AIRFLOW_CTX_TASK_ID='load_dataframe_into_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T08:43:05.401349+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T08:43:05.401349+00:00'
[2023-10-22T08:43:19.200+0000] {base.py:73} INFO - Using connection ID 'postgresql_db' for task execution.
[2023-10-22T08:43:19.202+0000] {logging_mixin.py:151} INFO - Engine(postgresql://diwahsap:***@ep-falling-leaf-21500535.ap-southeast-1.aws.neon.tech:5432/dibimbing?__extra__=%7B%7D)
[2023-10-22T08:43:19.208+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_day18.py", line 101, in load_dataframe_into_postgresql
    df.to_sql('public.coba',
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 768, in to_sql
    with pandasSQL_builder(con, schema=schema, need_transaction=True) as pandas_sql:
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 832, in pandasSQL_builder
    return SQLDatabase(con, schema, need_transaction)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1536, in __init__
    con = create_engine(con)
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 514, in create_engine
    u = _url.make_url(url)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 738, in make_url
    return _parse_url(name_or_url)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 799, in _parse_url
    raise exc.ArgumentError(
sqlalchemy.exc.ArgumentError: Could not parse SQLAlchemy URL from string 'dimas:9WsVuj5xhDlF@ep-falling-leaf-21500535.ap-southeast-1.aws.neon.tech/dibimbing'
[2023-10-22T08:43:19.227+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_day18, task_id=load_dataframe_into_postgresql, execution_date=20231022T084305, start_date=20231022T084318, end_date=20231022T084319
[2023-10-22T08:43:19.248+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 184 for task load_dataframe_into_postgresql (Could not parse SQLAlchemy URL from string 'dimas:9WsVuj5xhDlF@ep-falling-leaf-21500535.ap-southeast-1.aws.neon.tech/dibimbing'; 641)
[2023-10-22T08:43:19.280+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T08:43:19.307+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
