[2023-10-21T15:35:39.635+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_day18.merge_dataframes manual__2023-10-21T15:35:23.372764+00:00 [queued]>
[2023-10-21T15:35:39.666+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_day18.merge_dataframes manual__2023-10-21T15:35:23.372764+00:00 [queued]>
[2023-10-21T15:35:39.667+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-21T15:35:39.691+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): merge_dataframes> on 2023-10-21 15:35:23.372764+00:00
[2023-10-21T15:35:39.701+0000] {standard_task_runner.py:57} INFO - Started process 4245 to run task
[2023-10-21T15:35:39.707+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_day18', 'merge_dataframes', 'manual__2023-10-21T15:35:23.372764+00:00', '--job-id', '56', '--raw', '--subdir', 'DAGS_FOLDER/ETL_day18.py', '--cfg-path', '/tmp/tmpo4a0_syo']
[2023-10-21T15:35:39.714+0000] {standard_task_runner.py:85} INFO - Job 56: Subtask merge_dataframes
[2023-10-21T15:35:39.818+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_day18.merge_dataframes manual__2023-10-21T15:35:23.372764+00:00 [running]> on host 90cf752d844d
[2023-10-21T15:35:39.969+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kel11' AIRFLOW_CTX_DAG_ID='etl_day18' AIRFLOW_CTX_TASK_ID='merge_dataframes' AIRFLOW_CTX_EXECUTION_DATE='2023-10-21T15:35:23.372764+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-21T15:35:23.372764+00:00'
[2023-10-21T15:35:40.040+0000] {xcom.py:661} ERROR - Object of type DataFrame is not JSON serializable. If you are using pickle instead of JSON for XCom, then you need to enable pickle support for XCom in your *** config or make sure to decorate your object with attr.
[2023-10-21T15:35:40.042+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 91, in default
    return serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serde.py", line 143, in serialize
    data, classname, version, is_serialized = _serializers[qn].serialize(o)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/serialization/serializers/pandas.py", line 49, in serialize
    table = pa.Table.from_pandas(o)
  File "pyarrow/table.pxi", line 3557, in pyarrow.lib.Table.from_pandas
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 611, in dataframe_to_arrays
    arrays = [convert_column(c, f)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 611, in <listcomp>
    arrays = [convert_column(c, f)
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 598, in convert_column
    raise e
  File "/home/airflow/.local/lib/python3.8/site-packages/pyarrow/pandas_compat.py", line 592, in convert_column
    result = pa.array(col, type=type_, from_pandas=True, safe=safe)
  File "pyarrow/array.pxi", line 316, in pyarrow.lib.array
  File "pyarrow/array.pxi", line 83, in pyarrow.lib._ndarray_to_array
  File "pyarrow/error.pxi", line 123, in pyarrow.lib.check_status
pyarrow.lib.ArrowTypeError: ("Expected bytes, got a 'Timestamp' object", 'Conversion failed for column lastUpdated with type object')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_day18.py", line 80, in merge_dataframes
    return context['ti'].xcom_push(key='merged_df', value=merged_df)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 77, in wrapper
    return func(*args, session=session, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 2477, in xcom_push
    XCom.set(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/session.py", line 74, in wrapper
    return func(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 244, in set
    value = cls.serialize_value(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/xcom.py", line 659, in serialize_value
    return json.dumps(value, cls=XComEncoder).encode("UTF-8")
  File "/usr/local/lib/python3.8/json/__init__.py", line 234, in dumps
    return cls(
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 104, in encode
    return super().encode(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "/usr/local/lib/python3.8/json/encoder.py", line 257, in iterencode
    return _iterencode(o, 0)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/utils/json.py", line 93, in default
    return super().default(o)
  File "/usr/local/lib/python3.8/json/encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type DataFrame is not JSON serializable
[2023-10-21T15:35:40.054+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_day18, task_id=merge_dataframes, execution_date=20231021T153523, start_date=20231021T153539, end_date=20231021T153540
[2023-10-21T15:35:40.070+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 56 for task merge_dataframes (Object of type DataFrame is not JSON serializable; 4245)
[2023-10-21T15:35:40.098+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-21T15:35:40.128+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
