[2023-10-22T08:44:43.717+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_day18.load_dataframe_into_postgresql manual__2023-10-22T08:44:23.997133+00:00 [queued]>
[2023-10-22T08:44:43.731+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_day18.load_dataframe_into_postgresql manual__2023-10-22T08:44:23.997133+00:00 [queued]>
[2023-10-22T08:44:43.732+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-22T08:44:43.746+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_dataframe_into_postgresql> on 2023-10-22 08:44:23.997133+00:00
[2023-10-22T08:44:43.752+0000] {standard_task_runner.py:57} INFO - Started process 695 to run task
[2023-10-22T08:44:43.755+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_day18', 'load_dataframe_into_postgresql', 'manual__2023-10-22T08:44:23.997133+00:00', '--job-id', '190', '--raw', '--subdir', 'DAGS_FOLDER/ETL_day18.py', '--cfg-path', '/tmp/tmpennohdo5']
[2023-10-22T08:44:43.759+0000] {standard_task_runner.py:85} INFO - Job 190: Subtask load_dataframe_into_postgresql
[2023-10-22T08:44:43.810+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_day18.load_dataframe_into_postgresql manual__2023-10-22T08:44:23.997133+00:00 [running]> on host 90cf752d844d
[2023-10-22T08:44:43.893+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kel11' AIRFLOW_CTX_DAG_ID='etl_day18' AIRFLOW_CTX_TASK_ID='load_dataframe_into_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T08:44:23.997133+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T08:44:23.997133+00:00'
[2023-10-22T08:44:43.961+0000] {base.py:73} INFO - Using connection ID 'postgresql_db' for task execution.
[2023-10-22T08:44:43.964+0000] {logging_mixin.py:151} INFO - Engine(postgresql://diwahsap:***@ep-falling-leaf-21500535.ap-southeast-1.aws.neon.tech:5432/dibimbing?__extra__=%7B%7D)
[2023-10-22T08:44:45.820+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_day18.py", line 107, in load_dataframe_into_postgresql
    return hook.close()
AttributeError: 'PostgresHook' object has no attribute 'close'
[2023-10-22T08:44:45.833+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_day18, task_id=load_dataframe_into_postgresql, execution_date=20231022T084423, start_date=20231022T084443, end_date=20231022T084445
[2023-10-22T08:44:45.853+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 190 for task load_dataframe_into_postgresql ('PostgresHook' object has no attribute 'close'; 695)
[2023-10-22T08:44:45.904+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T08:44:45.927+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
