[2023-10-22T08:32:01.374+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: etl_day18.load_dataframe_into_postgresql manual__2023-10-22T08:31:46.043132+00:00 [queued]>
[2023-10-22T08:32:01.391+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: etl_day18.load_dataframe_into_postgresql manual__2023-10-22T08:31:46.043132+00:00 [queued]>
[2023-10-22T08:32:01.391+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2023-10-22T08:32:01.409+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): load_dataframe_into_postgresql> on 2023-10-22 08:31:46.043132+00:00
[2023-10-22T08:32:01.414+0000] {standard_task_runner.py:57} INFO - Started process 304 to run task
[2023-10-22T08:32:01.418+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'etl_day18', 'load_dataframe_into_postgresql', 'manual__2023-10-22T08:31:46.043132+00:00', '--job-id', '148', '--raw', '--subdir', 'DAGS_FOLDER/ETL_day18.py', '--cfg-path', '/tmp/tmpbpne1_nb']
[2023-10-22T08:32:01.423+0000] {standard_task_runner.py:85} INFO - Job 148: Subtask load_dataframe_into_postgresql
[2023-10-22T08:32:01.472+0000] {task_command.py:415} INFO - Running <TaskInstance: etl_day18.load_dataframe_into_postgresql manual__2023-10-22T08:31:46.043132+00:00 [running]> on host 90cf752d844d
[2023-10-22T08:32:01.648+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='kel11' AIRFLOW_CTX_DAG_ID='etl_day18' AIRFLOW_CTX_TASK_ID='load_dataframe_into_postgresql' AIRFLOW_CTX_EXECUTION_DATE='2023-10-22T08:31:46.043132+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2023-10-22T08:31:46.043132+00:00'
[2023-10-22T08:32:01.712+0000] {base.py:73} INFO - Using connection ID 'postgresql_db' for task execution.
[2023-10-22T08:32:01.715+0000] {logging_mixin.py:151} INFO - Engine(postgresql://diwahsap:***@ep-falling-leaf-21500535.ap-southeast-1.aws.neon.tech:5432/dibimbing?__extra__=%7B%7D)
[2023-10-22T08:32:01.740+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/ETL_day18.py", line 101, in load_dataframe_into_postgresql
    df.to_sql('public.latest', "postgres://diwahsap:Yj7lGFtyH3sQ@ep-falling-leaf-21500535.ap-southeast-1.aws.neon.tech/dibimbing", if_exists='replace', index=False)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/core/generic.py", line 2878, in to_sql
    return sql.to_sql(
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 768, in to_sql
    with pandasSQL_builder(con, schema=schema, need_transaction=True) as pandas_sql:
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 832, in pandasSQL_builder
    return SQLDatabase(con, schema, need_transaction)
  File "/home/airflow/.local/lib/python3.8/site-packages/pandas/io/sql.py", line 1536, in __init__
    con = create_engine(con)
  File "<string>", line 2, in create_engine
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/deprecations.py", line 375, in warned
    return fn(*args, **kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/create.py", line 518, in create_engine
    entrypoint = u._get_entrypoint()
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/engine/url.py", line 662, in _get_entrypoint
    cls = registry.load(name)
  File "/home/airflow/.local/lib/python3.8/site-packages/sqlalchemy/util/langhelpers.py", line 343, in load
    raise exc.NoSuchModuleError(
sqlalchemy.exc.NoSuchModuleError: Can't load plugin: sqlalchemy.dialects:postgres
[2023-10-22T08:32:01.762+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=etl_day18, task_id=load_dataframe_into_postgresql, execution_date=20231022T083146, start_date=20231022T083201, end_date=20231022T083201
[2023-10-22T08:32:01.784+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 148 for task load_dataframe_into_postgresql (Can't load plugin: sqlalchemy.dialects:postgres; 304)
[2023-10-22T08:32:01.806+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2023-10-22T08:32:01.832+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
